version: "3.8"

services:
  core:
    image: utngypisal/fintools-core:latest
    container_name: core-service
    restart: always
    ports:
      - 8101:8101
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
  khqr:
    image: utngypisal/fintools-khqr:latest
    container_name: khqr-service
    restart: always
    ports:
      - 8102:8102
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
  frontend:
    image: utngypisal/fintools-frontend:latest
    container_name: frontend-service
    ports:
      - 8100:80
    volumes:
      - ./frontend/:/opt/frontend
