version: "3.8"

services:
  khqr:
    image: tools/khqr
    build: tools.khqr
    restart: always
    env_file: ./.env
    ports:
      - 8081:8081
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
    environment:
      - SPRING_PROFILES_ACTIVE=$ENVIRONMENT
  tools:
    depends_on: khqr
    image: tools/main
    build: core
    restart: always
    env_file: ./.env
    ports:
      - $SPRING_HOST_PORT:$SPRING_DOCKER_PORT
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
    environment:
      - SPRING_PROFILES_ACTIVE=$ENVIRONMENT
