version: "3.8"

services:
  core:
    image: "core:v0.1.0"
    container_name: core
    build: core
    restart: always
    # env_file: ./.env
    ports:
      - 8101:8101
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
    environment:
    - SPRING_PROFILES_ACTIVE=$ENVIRONMENT
    - SPRING_DATASOURCE_URL=$DB_URL
    - SPRING_DATASOURCE_USERNAME=$DB_USER
    - SPRING_DATASOURCE_PASSWORD=$DB_PASSWORD
  khqr:
    image: "khqr:v0.1.0"
    container_name: khqr
    build: tools.khqr
    restart: always
    # env_file: ./.env
    ports:
      - 8102:8102
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
    environment:
      - SPRING_PROFILES_ACTIVE=$ENVIRONMENT
      - SPRING_DATASOURCE_URL=$DB_URL
      - SPRING_DATASOURCE_USERNAME=$DB_USER
      - SPRING_DATASOURCE_PASSWORD=$DB_PASSWORD
  frontend:
    image: "frontend:v0.1.0"
    container_name: frontend
    build: frontend
    ports:
      - ${SPRING_HOST_PORT:8100}:${SPRING_DOCKER_PORT:80}
    volumes:
      - ./frontend/:/opt/frontend